FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["src/TaskManager.API/TaskManager.csproj", "src/TaskManager.API/"]
COPY ["src/BaseLibrary/BaseLibrary.csproj", "src/BaseLibrary/"]
COPY ["src/ClientLibrary/ClientLibrary.csproj", "src/ClientLibrary/"]
RUN dotnet restore "src/TaskManager.API/TaskManager.csproj"

COPY . .
WORKDIR "/src/src/TaskManager.API"
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaskManager.dll"]